[project]
name = "water_shuffle"
version = "0.0.1"
dependencies = [
    "mdtraj",
    "scipy",
    "numpy",
]

[tool.pytest.ini_options]
pythonpath = [
 "."
]

[project.scripts]
water-shuffle = "water_shuffle:cli"

